name: my first workflow | shell script

on:
   workflow_dispatch:
   pull_request:
   push:
    branches: 
     - main
     
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: list files
              run:  ls -ltra

            - name: run shell script
              run:
                |
                chmod +x script.sh
                ./script.sh

            - uses: actions/upload-artifact@v7
              with:
               name: my-artifact
               path: dragon.txt

    sec_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: list files
              run:  ls -ltra

            - name: run shell script
              run:
                |
                chmod +x script.sh
                ./script.sh


       

