name: matrix startegy

on: push

jobs:
    run-image:
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-20, windows-latest]
                images: [hello-world, alpine]
        runs-on: ${{ matrix.os }}
        steps:
            - name: docker info
              run: docker info

            - name: run image
              run: docker run ${{ matrix.images }}


  