name: setup node

on: push

jobs:
    setup-node:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, ubuntu-22.04]
                node: [16,20,18]


            steps:
                - name: print env info
                  run: |
                   echo "running on os ${{ matrix.os }}"
                   echo "node version: ${{ matrix.node }}"

               
                - name: setup node
                  uses: actions/setup-node@v7
                  with:
                   node-version: ${{ matrix.node }}

                - name: run linix commands
                  run: |
                   uname -a
                   node -v
                   echo "hello from matrix job"


